CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    email character varying(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT "UQ_USER_EMAIL" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    description character varying(1000) NOT NULL,
    available boolean NOT NULL,
    owner bigint NOT NULL,
    request bigint,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.item_requests
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(1000) NOT NULL,
    requestor bigint NOT NULL,
    created timestamp without time zone NOT NULL,
    CONSTRAINT pk_item_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    item bigint NOT NULL,
    booker bigint NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.comments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text character varying(1000) NOT NULL,
    item_id bigint NOT NULL,
    author_id bigint NOT NULL,
    created timestamp without time zone NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);


ALTER TABLE public.items DROP CONSTRAINT IF EXISTS fk_items_to_users;
ALTER TABLE IF EXISTS public.items
    ADD CONSTRAINT fk_items_to_users FOREIGN KEY (owner)
    REFERENCES public.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE public.items DROP CONSTRAINT IF EXISTS fk_items_to_item_requests;
ALTER TABLE IF EXISTS public.items
    ADD CONSTRAINT fk_items_to_item_requests FOREIGN KEY (request)
    REFERENCES public.item_requests (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE public.item_requests DROP CONSTRAINT IF EXISTS fk_item_requests_to_users;
ALTER TABLE IF EXISTS public.item_requests
    ADD CONSTRAINT fk_item_requests_to_users FOREIGN KEY (requestor)
    REFERENCES public.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS fk_bookings_to_users;
ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_bookings_to_users FOREIGN KEY (booker)
    REFERENCES public.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS fk_bookings_to_items;
ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT fk_bookings_to_items FOREIGN KEY (item)
    REFERENCES public.items (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE public.comments DROP CONSTRAINT IF EXISTS fk_comments_to_items;
ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_to_items FOREIGN KEY (item_id)
    REFERENCES public.items (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE public.comments DROP CONSTRAINT IF EXISTS fk_comments_to_users;
ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT fk_comments_to_users FOREIGN KEY (author_id)
    REFERENCES public.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;